#Requires -RunAsAdministrator
<#
.SYNOPSIS
  Installs the InvMon agent as a Windows service.
.DESCRIPTION
  Copies invmon-agent.exe to Program Files, creates the ProgramData data
  directory with a restricted ACL, writes agent.yaml from the supplied
  parameters, and registers the InvMonAgent service (automatic delayed start).
.PARAMETER ServerUrl
  Agent API base URL, e.g. https://invmon.corp.local:8443
.PARAMETER EnrollToken
  Enrollment token (imenr_...) issued in the admin UI.
.PARAMETER CaFile
  Path to a PEM CA certificate to copy alongside the agent and trust. Optional.
.PARAMETER Start
  Start the service immediately after installation.
.EXAMPLE
  .\install.ps1 -ServerUrl https://invmon.corp.local:8443 -EnrollToken imenr_xxx -CaFile .\ca.pem -Start
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string]$ServerUrl,
    [Parameter(Mandatory = $true)][string]$EnrollToken,
    [string]$CaFile,
    [switch]$Start
)

$ErrorActionPreference = 'Stop'
$here = Split-Path -Parent $MyInvocation.MyCommand.Path

$installDir = Join-Path $env:ProgramFiles 'InvMon\Agent'
$dataDir = Join-Path $env:ProgramData 'InvMon\Agent'

Write-Host "Installing InvMon agent to $installDir"
New-Item -ItemType Directory -Force -Path $installDir | Out-Null
Copy-Item -Path (Join-Path $here 'invmon-agent.exe') -Destination $installDir -Force

New-Item -ItemType Directory -Force -Path $dataDir, (Join-Path $dataDir 'logs') | Out-Null
icacls $dataDir /inheritance:r /grant:r 'SYSTEM:(OI)(CI)F' 'Administrators:(OI)(CI)F' | Out-Null

$caPath = Join-Path $dataDir 'ca.pem'
if ($CaFile) {
    Copy-Item -Path $CaFile -Destination $caPath -Force
}

# Render agent.yaml. Values are single-quoted; escape embedded single quotes.
function Yaml-Quote([string]$s) { "'" + ($s -replace "'", "''") + "'" }
$configPath = Join-Path $dataDir 'agent.yaml'
@"
# Generated by install.ps1
server_url: $(Yaml-Quote $ServerUrl)
ca_file: $(Yaml-Quote $caPath)
enroll_token: $(Yaml-Quote $EnrollToken)
proxy: ''
log_level: info
"@ | Set-Content -Path $configPath -Encoding UTF8

$exe = Join-Path $installDir 'invmon-agent.exe'
& $exe service install
if ($LASTEXITCODE -ne 0) { throw "service install failed ($LASTEXITCODE)" }

if ($Start) {
    & $exe service start
    if ($LASTEXITCODE -ne 0) { throw "service start failed ($LASTEXITCODE)" }
}

Write-Host ''
Write-Host 'InvMon agent installed.' -ForegroundColor Green
Write-Host "  Config: $configPath"
Write-Host "  Logs:   $(Join-Path $dataDir 'logs')"
